### ISSUE TITLE
package __init__.py 's __version__ not set

### ISSUE THREAD

**Issue by jayvdb** [chfw/yehua#4]
The generated `<package>.yml` contains
```yml
version: "0.0.1"
release: "0.0.1"
```
and that is used by setup.py, however that version is not provided in the installed package's `__version__`.

The easiest solution is for `__init__.py` to use `pkg_resources` to fetch its own version (c.f. https://stackoverflow.com/a/17638236/5037965), but IMO that is an unacceptable solution as it requires a dependency on `pkg_resources` and it is an expensive call in order to find something which was known at build time.

Lots of other approaches, such as storing it in a `_version.py` or `VERSION` file, are more suitable.

And then there are the hard problems of providing a useful version identifier at runtime for a specific commit.
(https://github.com/twisted/incremental , https://github.com/warner/python-versioneer , etc)

**Comment by chfw** [comment]
I saw many other packages had __version__, __author__ and etc set in __init__.py. Could you enlighten me on their usage? As you mentioned, those info could be obtained in setup.py anyway.

**Comment by jayvdb** [comment]
They allow

1. the package to know its own version, e.g. reporting the version to the user
2. other python code to use the package version to identify if a feature exists (and is usable) in the installed package.

There are several peps about these information 'dunder' attributes, such as https://www.python.org/dev/peps/pep-0396/ and https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names

**Comment by chfw** [comment]
I see. I didn't realise that such a version could bring a lot of technical discussion on it. Let me fix it for now and think of a permanent solution. At the moment, I am more inclined to templates a version.py file like the way I have done to setup.py.
